import Link from "next/link";
import Image from "../../_components/asset-image";
import Icon from "../../_components/icon";
import { professionals } from "../../professionals/leadership";
import { regtechSolutions } from "@/content/regtech-solutions";
import Enquiry from "../enquiry";
import sharedStyles from "../digital-business-solutions/digital-business.module.css";
import regtechStyles from "./regtech.module.css";
const styles = { ...sharedStyles, ...Object.fromEntries(Object.entries(regtechStyles).map(([key, value]) => [key, [sharedStyles[key], value].filter(Boolean).join(' ')])) };

export const metadata = {
  title: "RegTech & Compliance Technology",
  description: "Connect regulatory expertise with technology through compliance management, monitoring, calendars, licensing, risk governance and sustainability tools.",
};

const challenges = [["file", "Keep up with frequent regulatory changes"], ["network", "Manage multi-jurisdictional compliance"], ["document", "Track licensing and approvals"], ["gear", "Ensure accurate and timely reporting"], ["person", "Reduce compliance risk"], ["shield", "Build a culture of good governance"]];
const steps = [["Assess", "Understand your regulatory and business needs"], ["Design", "Develop tailored compliance solutions"], ["Implement", "Deploy and integrate with your systems"], ["Monitor", "Track, report and refine"], ["Support", "Provide continuous advisory and updates"]];
const sectors = [["building", "Banking & Financial Services", "financial-services"], ["shield", "FinTech & NBFC", "fintech-and-digital-finance"], ["gear", "Manufacturing", "manufacturing"], ["shield", "Healthcare & Life Sciences", "healthcare-and-pharma"], ["building", "Real Estate & Construction", "real-estate-and-construction"], ["laptop", "E-Commerce & Technology", "e-commerce"]];
const related = [["Regulatory & Compliance Advisory", "/services/regulatory-and-compliance"], ["Risk & Governance", "/services/risk-governance-and-forensic-advisory"], ["FEMA / FDI Advisory", "/services/fema-fdi-and-foreign-exchange-advisory"], ["Company Law Advisory", "/services/corporate-advisory"], ["Business Advisory", "/services/business-advisory-and-consulting"], ["Policy & Legal Research", "/insights/legal-updates"]];
const insights = [["Regulatory perspectives", "Explore the evolving RegTech landscape", "/images/india-presence/mumbai.jpg", "/insights/legal-updates"], ["Planning & compliance", "Compliance calendars: from deadlines to action", "/Professional & Business Services .png", "/insights/compliance-calendar"], ["Sustainability perspectives", "ESG reporting and business priorities", "/nergy, Power & Renewables .png", "/insights/articles"]];
const faqs = [
  ["How does RegTech help in compliance management?", "RegTech connects compliance information, responsibilities and workflows. It can help teams organise obligations, follow deadlines, record evidence and identify items that need review, alongside professional judgement and oversight."],
  ["Can your solutions handle multi-jurisdictional compliance?", "We assess the jurisdictions, entities and obligations relevant to your business before defining the scope. Workflows can then be organised by location and responsibility, with local requirements reviewed by the appropriate professionals."],
  ["Do you provide custom compliance solutions?", "The solution is shaped around your sector, existing systems, priorities and reporting needs. We agree the workflows, integration requirements and delivery plan before implementation."],
  ["How do you ensure data security and confidentiality?", "We discuss access, confidentiality and data handling requirements at the outset. Security controls, responsibilities and review arrangements form part of the agreed solution design."],
  ["Do you offer ongoing support after implementation?", "Training, monitoring, advisory updates and ongoing improvements can be included in the engagement. We agree the support scope and responsibilities with you before implementation."],
];
function TextLink({ href, children }: { href: string; children: React.ReactNode }) {
  return <Link className={styles.textLink} href={href}>{children}<Icon name="arrow" /></Link>;
}

export default function RegtechPage() {
  return <div className={styles.page}>
    <section className={styles.hero} aria-labelledby="regtech-title">
      <Image src="/FinTech & Digital Finance .png" alt="Digital finance and connected regulatory technology" fill preload sizes="100vw" />
      <div className={`${styles.wrap} ${styles.heroInner}`}>
        <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/">Home</Link><span aria-hidden="true">›</span><Link href="/technology-and-digital-solutions">Technology &amp; Digital Solutions</Link><span aria-hidden="true">›</span><span aria-current="page">RegTech & Compliance Technology</span></nav>
        <div className={styles.heroCopy}><span className={styles.eyebrow}>RegTech &amp; Compliance Technology</span><h1 id="regtech-title">Stay Ahead.<br />Stay Compliant.</h1><p className={styles.tagline}>Smarter compliance for a more resilient tomorrow.</p><p>We combine legal, regulatory and domain expertise with technology to help businesses navigate complex regulatory landscapes with confidence and clarity.</p><Link className={styles.button} href="#enquiry">Discuss Your Compliance Requirements <Icon name="arrow" /></Link></div>
        <aside className={styles.motto}>Technology<br />enabling trust<br />in a complex<br />regulatory<br />world.<span>Astronis<br />Global.</span></aside>
      </div>
    </section>

    <section className={styles.challengeSection}><div className={`${styles.wrap} ${styles.challenges}`}><div><h2>Regulatory Challenges.<br />Practical Solutions.</h2><p>Regulatory change is constant. We help you stay compliant, reduce risk and build stronger governance through technology-enabled solutions.</p><TextLink href="#approach">Explore Our Approach</TextLink></div><div className={styles.challengeItems}>{challenges.map(([icon, title]) => <div key={title}><Icon name={icon} /><h3>{title}</h3></div>)}</div></div></section>

    <section className={`${styles.wrap} ${styles.section}`} id="solutions"><div className={styles.sectionHeading}><div><span className={styles.eyebrow}>Clarity. Control. Confidence.</span><h2>Our RegTech &amp; Compliance Solutions</h2></div><TextLink href="/technology-and-digital-solutions">Explore All Solutions</TextLink></div><div className={styles.solutions}>{regtechSolutions.map((solution) => <article className={styles.card} id={solution.id} key={solution.id}><div className={styles.solutionImage}><Image src={solution.image} alt="" fill sizes="(max-width: 540px) 90vw, (max-width: 1000px) 30vw, 14vw" /><span className={styles.iconBadge}><Icon name={solution.icon} /></span></div><div className={styles.cardBody}><h3>{solution.title}</h3><p>{solution.description}</p><details className={styles.solutionDetail}><summary>Learn More <Icon name="arrow" /></summary><p>{solution.detail}</p><TextLink href={`?solution=${encodeURIComponent(solution.title)}#enquiry`}>Discuss this solution</TextLink></details></div></article>)}</div></section>

    <section className={styles.implementation} id="approach"><div className={styles.benefits}><h2>Why Choose Astronis</h2><ul>{["Deep regulatory expertise", "Technology-enabled solutions", "Industry-specific frameworks", "Practical and cost-effective", "Ongoing advisory support"].map((benefit) => <li key={benefit}><Icon name="shield" />{benefit}</li>)}</ul></div><div className={styles.steps}><span className={styles.eyebrow}>From ambition to action</span><h2>Our Implementation Approach</h2><ol>{steps.map(([title, body], index) => <li key={title}><span className={styles.stepNumber}>0{index + 1}</span><h3>{title}</h3><p>{body}</p></li>)}</ol></div><div className={styles.approachImage}><Image src="/images/india-presence/mumbai.jpg" alt="Modern commercial architecture" fill sizes="20vw" /><span>Compliance today.<br />Opportunities<br />tomorrow.</span></div></section>

    <div className={`${styles.wrap} ${styles.connections}`}><section><div className={styles.sectionHeading}><h2>Industries We Support</h2><TextLink href="/industries">View All Industries</TextLink></div><div className={styles.industries}>{sectors.map(([icon, title, slug]) => <Link href={`/industries/${slug}`} key={slug}><Icon name={icon} /><span>{title}</span></Link>)}</div></section><section><div className={styles.sectionHeading}><h2>Related Services</h2><TextLink href="/services">View All Services</TextLink></div><div className={styles.related}>{related.map(([title, href]) => <Link href={href} key={title}><Icon name="arrow" />{title}</Link>)}</div></section></div>

    <section className={styles.teamSection}><div className={styles.wrap}><div className={styles.sectionHeading}><div><span className={styles.eyebrow}>Connected expertise</span><h2>Technology Specialists</h2></div><TextLink href="/professionals">View All Professionals</TextLink></div><div className={styles.team}>{professionals.slice(0, 2).map((person) => <Link className={styles.person} key={person.slug} href={`/professionals/${person.slug}`}><div className={styles.portrait}><Image src={person.image} alt={person.name} fill sizes="(max-width: 540px) 90vw, 25vw" /></div><div><h3>{person.name}</h3><span>{person.role}</span><p>{person.expertise}</p><Icon name="arrow" /></div></Link>)}<Link className={styles.extendedTeam} href="/professionals"><Image src="/professional-collaboration-hero.png" alt="Our wider professional network" fill sizes="(max-width: 800px) 90vw, 40vw" /><div><span className={styles.eyebrow}>A multidisciplinary perspective</span><h3>Our Extended Team</h3><p>Legal, regulatory and business expertise, brought together around your needs.</p><span>Meet our professionals <Icon name="arrow" /></span></div></Link></div></div></section>

    <section className={`${styles.wrap} ${styles.section}`}><div className={styles.sectionHeading}><div><span className={styles.eyebrow}>Ideas for your next step</span><h2>Latest Insights</h2></div><TextLink href="/insights">View All Insights</TextLink></div><div className={styles.insights}>{insights.map(([category, title, image, href]) => <article className={styles.card} key={title}><div className={styles.insightImage}><Image src={image} alt="" fill sizes="(max-width: 540px) 90vw, 30vw" /></div><div className={styles.cardBody}><span className={styles.eyebrow}>{category}</span><h3>{title}</h3><TextLink href={href}>Read More</TextLink></div></article>)}</div></section>

    <section className={styles.faqSection}><div className={`${styles.wrap} ${styles.faqGrid}`}><div><span className={styles.eyebrow}>Your questions, answered</span><h2>Frequently Asked Questions</h2><p>Clear guidance on compliance technology, implementation and ongoing support.</p><TextLink href="/faqs">View All FAQs</TextLink></div><div className={styles.faqs}>{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></div></section>

    <section className={styles.enquirySection} id="enquiry"><div className={`${styles.wrap} ${styles.enquiryGrid}`}><div className={styles.enquiryCopy}><span className={styles.eyebrow}>Build confidence into compliance</span><h2>Discuss Your Compliance or RegTech Requirements</h2><p>Let&apos;s explore how we can help you build a stronger, more compliant and future-ready business.</p><div className={styles.enquiryImage}><Image src="/Technology, IT & ITES .png" alt="Digital technology connecting business systems" fill sizes="(max-width: 800px) 90vw, 40vw" /></div><a href="tel:+919311664455"><Icon name="phone" />+91 93116 64455</a><a href="mailto:advisory@astronisglobal.com"><Icon name="mail" />advisory@astronisglobal.com</a></div><div className={styles.formPanel}><span className={styles.eyebrow}>Start a conversation</span><h3>Tell us about your requirements.</h3><p>Our team will get in touch for a detailed discussion.</p><Enquiry defaultService="RegTech & Compliance Technology" /></div></div></section>
  </div>;
}
