export const clients = [
  { name: "Vedanta", descriptor: "Transforming for good", className: "vedanta", logo: "/clients/vedanta.png" },
  { name: "DLF", descriptor: "Building India", className: "dlf", logo: "/clients/dlf.png" },
  { name: "Tata", descriptor: "", className: "tata", logo: "/clients/tata.png" },
  { name: "Godrej", descriptor: "", className: "godrej", logo: "/clients/godrej.png" },
  { name: "ITC Limited", descriptor: "", className: "itc", logo: "/clients/itc-limited.png" },
  { name: "Flipkart", descriptor: "", className: "flipkart", logo: "/clients/flipkart.png" },
  { name: "Jindal Steel & Power", descriptor: "", className: "jindal", logo: "/clients/jindal-steel-and-power.png" },
  { name: "Max Healthcare", descriptor: "", className: "max", logo: "/clients/max-healthcare.png" },
  { name: "Adani", descriptor: "", className: "adani", logo: "/clients/adani.png" },
  { name: "Maruti Suzuki", descriptor: "", className: "maruti", logo: "/clients/maruti-suzuki.png" },
  { name: "Bharti Enterprises", descriptor: "", className: "bharti", logo: "/clients/bharti-enterprises.png" },
  { name: "Reliance Industries", descriptor: "Limited", className: "reliance", logo: "/clients/reliance-industries.png" },
  { name: "HDFC Bank", descriptor: "", className: "hdfc", logo: "/clients/hdfc-bank.png" },
  { name: "ICICI Bank", descriptor: "", className: "icici", logo: "/clients/icici-bank.png" },
  { name: "Kotak Mahindra Bank", descriptor: "", className: "kotak", logo: "/clients/kotak-mahindra-bank.png" },
  { name: "EY", descriptor: "Building a better working world", className: "ey", logo: "/clients/ey.png" },
  { name: "pwc", descriptor: "", className: "pwc", logo: "/clients/pwc.png" },
  { name: "KPMG", descriptor: "", className: "kpmg", logo: "/clients/kpmg.png" },
  { name: "Grant Thornton", descriptor: "", className: "grant", logo: "/clients/grant-thornton.png" },
  { name: "Lupin", descriptor: "", className: "lupin", logo: "/clients/lupin.png" },
  { name: "Sun Pharma", descriptor: "", className: "sun", logo: "/clients/sun-pharma.png" },
  { name: "Coca-Cola", descriptor: "", className: "coca", logo: "/clients/coca-cola.png" },
  { name: "Blue Star", descriptor: "", className: "blue-star", logo: "/clients/blue-star.png" },
  { name: "Wipro", descriptor: "Applying thought", className: "wipro", logo: "/clients/wipro.png" },
] as const;
