export const dataAiPath = "/technology-and-digital-solutions/data-ai-and-automation";

export const dataAiSolutions = [
  { id: "artificial-intelligence-solutions", title: "Artificial Intelligence Solutions", icon: "bulb", description: "Practical AI applications for business, legal and regulatory operations.", detail: "Identify suitable use cases, assess data readiness and develop an implementation roadmap with human review and clear success measures.", image: "/Banner - Indus - Artificial Intelligence .png" },
  { id: "data-analytics-and-visualisation", title: "Data Analytics & Visualisation", icon: "chart", description: "Transform data into meaningful insights.", detail: "Organise and analyse information from your business systems, then communicate patterns through accessible reports and visualisations.", image: "/Technology, IT & ITES .png" },
  { id: "intelligent-automation-rpa", title: "Intelligent Automation (RPA)", icon: "gear", description: "Automate repetitive tasks and improve consistency.", detail: "Map repetitive activities, define rules and exceptions, and introduce automation with monitoring and appropriate approval controls.", image: "/Manufacturing & Industrial .png" },
  { id: "ai-assisted-research", title: "AI-Assisted Research", icon: "search", description: "Support deeper legal and regulatory research.", detail: "Use assisted search and summarisation within a reviewed research workflow. Professionals verify sources and outputs before relying on them.", image: "/Part-14 .png" },
  { id: "predictive-insights", title: "Predictive Insights", icon: "target", description: "Explore trends and anticipate emerging business needs.", detail: "Use historical data to explore likely patterns and scenarios, with assumptions, uncertainty and model limitations made clear to decision-makers.", image: "/FinTech & Digital Finance .png" },
  { id: "regulatory-data-intelligence", title: "Regulatory Data Intelligence", icon: "globe", description: "Monitor and analyse regulatory developments.", detail: "Bring regulatory information into a structured view to support impact assessment, prioritisation and professional review.", image: "/Telecommunications & Digital Infrastructure .png" },
  { id: "business-intelligence-dashboards", title: "Business Intelligence Dashboards", icon: "laptop", description: "Clear performance insights for better decision-making.", detail: "Connect agreed data sources and metrics in dashboards that help teams understand performance, exceptions and priorities. Refresh schedules depend on the source systems.", image: "/Technology, IT & ITES .png" },
  { id: "process-optimisation", title: "Process Optimisation", icon: "network", description: "Redesign processes using data and automation.", detail: "Identify bottlenecks, simplify handoffs and measure improvements against agreed operational goals before scaling changes.", image: "/Professional & Business Services .png" },
] as const;
