export const legalTechnologyPath = "/technology-and-digital-solutions/legal-technology";

export const legalTechnologySolutions = [
  { id: "contract-lifecycle-management", title: "Contract Lifecycle Management", icon: "file", description: "Create, review, manage and track contracts efficiently.", detail: "Connect drafting, review, approvals, execution and renewal tracking through a structured contract workflow with clear responsibilities.", image: "/Part-6 .png" },
  { id: "document-management", title: "Document Management", icon: "folder", description: "Searchable and organised legal document repositories.", detail: "Bring documents, versions and access permissions together so teams can find the right information and maintain an organised record of their work.", image: "/Part-14 .png" },
  { id: "matter-case-management", title: "Matter / Case Management", icon: "scale", description: "Track matters, responsibilities and timelines in one place.", detail: "Coordinate litigation and advisory matters with organised case files, task ownership, key dates and status reporting.", image: "/legal-professionals-hero.png" },
  { id: "legal-workflow-automation", title: "Legal Workflow Automation", icon: "network", description: "Automate routine tasks and approvals to improve productivity.", detail: "Define repeatable workflows for intake, review, approvals and reporting, with escalation paths and human oversight where needed.", image: "/Technology, IT & ITES .png" },
  { id: "e-discovery-and-evidence-management", title: "e-Discovery & Evidence Management", icon: "search", description: "Organise and review electronic evidence with confidence.", detail: "Support structured collection, indexing and review of electronic records, with agreed access controls and evidence-handling procedures.", image: "/Professional & Business Services .png" },
  { id: "knowledge-management", title: "Knowledge Management", icon: "document", description: "Make legal knowledge, precedents and insights accessible.", detail: "Build a shared knowledge base of templates, precedents and research, with ownership and review processes to keep information useful.", image: "/Part-18 .png" },
  { id: "ai-assisted-legal-research", title: "AI-Assisted Legal Research", icon: "bulb", description: "Support research and analysis with professional oversight.", detail: "Explore AI-assisted search and summarisation within an agreed workflow. Sources and outputs are checked by professionals before they inform legal work.", image: "/Banner - Indus - Artificial Intelligence .png" },
] as const;
