export const regtechPath = "/technology-and-digital-solutions/regtech-and-compliance-technology";

export const regtechSolutions = [
  { id: "compliance-management", title: "Compliance Management", icon: "shield", description: "Centralise and streamline your compliance obligations.", detail: "Organise obligations, assign responsibilities and track evidence in one coordinated workflow, with visibility across teams and entities.", image: "/Part-8 .png" },
  { id: "regulatory-monitoring-and-alerts", title: "Regulatory Monitoring & Alerts", icon: "file", description: "Stay informed about relevant regulatory changes.", detail: "Define the developments that matter to your business, organise updates and route them to the right people for review and action.", image: "/FinTech & Digital Finance .png" },
  { id: "compliance-calendar", title: "Compliance Calendar", icon: "calendar", description: "Keep filings, renewals and deadlines in view.", detail: "Bring due dates, owners and reminders together in a shared calendar, with a clear record of upcoming and completed tasks.", image: "/Professional & Business Services .png" },
  { id: "licensing-and-approval-tracking", title: "Licensing & Approval Tracking", icon: "document", description: "Track licences and approvals from start to finish.", detail: "Follow applications, supporting documents, status updates and renewal dates through a structured approval workflow.", image: "/Part-6 .png" },
  { id: "policy-and-regulatory-intelligence", title: "Policy & Regulatory Intelligence", icon: "chart", description: "Actionable insights for informed decision-making.", detail: "Connect policy developments with business priorities through organised research, impact assessments and practical reporting.", image: "/Technology, IT & ITES .png" },
  { id: "risk-and-governance-technology", title: "Risk & Governance Technology", icon: "target", description: "Strengthen oversight, accountability and controls.", detail: "Keep risk registers, control reviews, ownership and escalation pathways connected so decision-makers can follow the issues that need attention.", image: "/Banking & Financial Services .png" },
  { id: "esg-and-sustainability-tools", title: "ESG & Sustainability Tools", icon: "globe", description: "Support your sustainability reporting journey.", detail: "Organise ESG information, supporting evidence and reporting responsibilities around the frameworks relevant to your organisation.", image: "/nergy, Power & Renewables .png" },
] as const;
