import Link from "next/link";
import Image from "../_components/asset-image";
import Icon from "../_components/icon";
import styles from "./hub.module.css";

export function Action({ href, children, secondary = false }: { href: string; children: React.ReactNode; secondary?: boolean }) {
  return <Link href={href} className={`${styles.action} ${secondary ? styles.secondary : ""}`}>{children}<Icon name="arrow" /></Link>;
}
export function ServicesHero() {
  const nodes = ["Corporate", "Regulatory", "Legal", "Transactions", "Compliance", "Global Advisory", "Technology", "Risk"];
  return <section className={styles.hero}><Image src="/images/services/hero.webp" alt="" fill preload sizes="100vw" className={styles.heroBackground} /><div className="container"><nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span aria-current="page">Services</span></nav><div className={styles.heroGrid}><div><span className={styles.eyebrow}>INTEGRATED ADVISORY SERVICES</span><h1>Integrated Corporate, Legal, Regulatory <em>&amp; Business Advisory</em> Services</h1><p className={styles.heroCopy}>End-to-end advisory for corporate structuring, regulations, transactions, compliance and growth — in India and across international markets.</p><div className={styles.actions}><Action href="#all-services">Explore Our Services</Action><Action href="#consultation" secondary>Speak With an Advisor</Action></div></div><div className={styles.ecosystem} role="img" aria-label="Astronis Advisory connects corporate, regulatory, legal, transactions, compliance, global advisory, technology and risk expertise"><div className={styles.orbit} /><div className={styles.orbitInner} /><svg viewBox="0 0 480 480" aria-hidden="true">{nodes.map((node, i) => { const angle = i * Math.PI / 4 - Math.PI / 2; return <line key={node} x1="240" y1="240" x2={240 + Math.cos(angle) * 178} y2={240 + Math.sin(angle) * 178} />; })}</svg><div className={styles.centralNode}><span>A</span><strong>Astronis<br />Advisory</strong><small>CONNECTED EXPERTISE</small></div>{nodes.map((node, i) => <span key={node} className={styles.node} style={{ "--i": i } as React.CSSProperties}>{node}</span>)}<span className={styles.ecosystemCaption}>A broader perspective. A coordinated approach.</span></div></div><div className={styles.heroBadges}>{["Corporate Advisory", "Regulatory Compliance", "M&A", "FEMA & FDI", "Intellectual Property", "Banking & RBI", "Technology & Privacy", "ESG"].map(label => <span key={label}><i />{label}</span>)}</div></div></section>;
}
export function ExpertiseBanner() {
  return <aside className={styles.expertise}><span className={styles.eyebrow}>CONNECTED THINKING. PRACTICAL DIRECTION.</span><h2>Complex business challenges<br />require connected expertise.</h2><p>Legal, financial and commercial decisions overlap. We bring the relevant perspectives into the same conversation, so your next step accounts for the wider business.</p><div>{["Legal", "Regulatory", "Commercial", "Strategic"].map((title, i) => <span key={title}><small>0{i + 1}</small>{title}<Icon name={["scale", "shield", "building", "chart"][i]} /></span>)}</div></aside>;
}
export function WhyAstronis() {
  const reasons = [["building", "Integrated Expertise", "Corporate, legal, regulatory and business perspectives brought together around your objectives."], ["chart", "Practical Business Perspective", "Advice shaped by operating realities, commercial priorities and the decisions your team needs to make."], ["people", "Multi-Sector Perspective", "Industry context across financial services, technology, manufacturing, healthcare and infrastructure."], ["globe", "Cross-Border Capability", "Coordinated support for international businesses entering India and Indian businesses expanding overseas."], ["shield", "Compliance-Focused Approach", "Identify obligations, allocate responsibilities and bring regulatory requirements into business planning."], ["file", "Long-Term Advisory", "Support that follows the business through establishment, transactions, change and ongoing obligations."]];
  return <section className={`${styles.section} ${styles.why}`}><div className="container"><span className={styles.eyebrow}>A BUSINESS-WIDE PERSPECTIVE</span><h2>Why Businesses Choose Astronis</h2><div className={styles.reasonGrid}>{reasons.map(([icon, title, description]) => <article key={title}><Icon name={icon} /><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>;
}
export function FinalCTA() {
  return <section className={styles.final}><div className="container"><span className={styles.eyebrow}>LET’S CONNECT THE DOTS</span><h2>Your business challenge may cross multiple disciplines.<br /><em>Our advice should too.</em></h2><p>Connect with Astronis for integrated corporate, regulatory, legal and strategic advisory.</p><div className={styles.actions}><Action href="#consultation">Schedule a Consultation</Action><Action href="/contact" secondary>Contact Our Team</Action></div></div></section>;
}
